# 101 NumPy Exercises for Data Analysis

## 说明

该文档是对[《101 NumPy Exercises for Data Analysis (Python)》](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)的学习笔记。现文档为 [NumPy数据分析练习](https://www.numpy.org.cn/article/advanced/numpy_exercises_for_data_analysis.html)（由[NumPy中文文档](https://www.numpy.org.cn/)翻译）。

#### **1. 导入numpy作为np，并查看版本**

- 难度等级：L1
- 问题：将numpy导入为 np 并打印版本号

In [2]:
import numpy as np
print(np.__version__)

1.15.4


#### **2. 如何创建一维数组？**

- 难度等级：L1
- 问题：创建从0到9的一维数字数组

In [9]:
# 以下省略 import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### **3. 如何创建一个布尔数组？**

- 难度等级：L1
- 问题：创建一个numpy数组元素值全为True（真）的数组

In [15]:
a = np.full((3, 3), True, dtype=bool)
print(a)
# print(help(np.full))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### **4. 如何从一维数组中提取满足指定条件的元素？**

- 难度等级：L1
- 问题：从a中提取所有的奇数

In [13]:
# 给定
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 第一种方式（适用于列表和数组）
b = [i for i in a if i % 2 == 1]
print(b)

# 第二种方式（适用于数组）
c = a[a % 2 == 1]
print(c)

[1, 3, 5, 7, 9]
[1 3 5 7 9]


#### **5. 如何用numpy数组中的另一个值替换满足条件的元素项？**

- 难度等级：L1
- 问题：将a中的所有奇数替换为-1

In [17]:
# 给定
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 第一种方式
b = a
b[b % 2 == 1] = -1
print(b)

# 第二种方式
c = []
for i in a:
    if i % 2 == 1:
        c.append(-1)
    else:
        c.append(i)
print(c)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


#### **6. 如何在不影响原始数组的情况下替换满足条件的元素项？**

- 难度等级：L2
- 问题：将a中的所有奇数替换为-1，而不改变a

In [18]:
# 给定
a = np.arange(10)
b = np.where(a % 2 == 1, -1, a)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### **7. 如何改变数组的形状？**

- 难度等级：L1
- 问题：将一维数组转换为2行的2维数组

In [22]:
# 给定
a = np.arange(10)
print(a)

b = a.reshape(2, 5)
print(b)

c = a.reshape(2, -1) # -1 表示自动填充
print(c)

d = a
d.shape = 2, 5
print(d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### **8. 如何垂直叠加两个数组？**

- 难度等级：L2
- 问题：垂直堆叠数组a和数组b

In [24]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# 方法一
add1 = np.concatenate([a, b], axis=0)

# 方法二
add2 = np.vstack([a, b])

# 方法三
add3 = np.r_[a, b]

print(a)
print(b)
print(add1)
print(add2)
print(add3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### **9. 如何水平叠加两个数组？**

- 难度等级：L2
- 问题：水平堆叠数组a和数组b

In [25]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# 方法一
add1 = np.concatenate([a, b], axis=1)

# 方法二
add2 = np.hstack([a, b])

# 方法三
add3 = np.c_[a, b]

print(a)
print(b)
print(add1)
print(add2)
print(add3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### **10. 如何在无硬编码的情况下生成numpy中的自定义序列？**

- 难度等级：L2
- 问题：创建以下模式而不使用硬编码。只使用numpy函数和下面的输入数组a。
- 给定：
    ```python
    a = np.array([1,2,3])
    ```
- 期望：
    ```python
    array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
    ```

In [28]:
a = np.array([1,2,3])
print(a)

b = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(b)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


#### **11. 如何获取两个numpy数组之间的公共项？**

- 难度等级：L2
- 问题：获取数组a和数组b之间的公共项

In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# 第一种列表的方式
c = []
for i in a:
    if (i in b) and (i not in c): # 注意要加上 not in c
        c.append(i)
print(c)
print(type(c))

# 第二种数组的方式
d = np.intersect1d(a, b) # 注意这里是1而不是l
print(d)

[2, 4]
<class 'list'>
[2 4]


#### **12. 如何从一个数组中删除存在于另一个数组中的项？**

- 难度等级：L2
- 问题：从数组a中删除数组b中的所有项

In [48]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# 第一种列表的方式
c = []
for i in a:
    if i not in b:
        c.append(i)
print(c)
print(type(c))

# 第二种数组的方式
d = np.setdiff1d(a, b)
print(d)
print(d.dtype)

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
int32


#### **13. 如何得到两个数组元素匹配的位置？**

- 难度等级：L2
- 问题：获取a和b元素匹配（相等）的位置

In [56]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# 第一种是列表的方式
c = []
for i in range(len(a)):
    if a[i] == b[i]:
        c.append(i)
print(c)
print(type(c))

# 第二种是数组的方式
d = np.where(a == b)
print(d)
print(type(d))
# 注意这里使用 d.dytpe 会报错

[1, 3, 5, 7]
<class 'list'>
(array([1, 3, 5, 7], dtype=int64),)
<class 'tuple'>


#### **14. 如何从numpy数组中提取给定范围内的所有数字？**

- 难度等级：L2
- 问题：获取5到10之间的所有项目

In [67]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# 第一种数组的方式
c = []
for i in a:
    if i <= 10 and i >= 5:
        c.append(i)
print(c)
print(type(c))

# 第二种数组的方式
# 方法一
index = np.where((a >= 5) & (a <= 10)) # 注意这里不能用 and 会报错
print(index)
print(a[index])

# 方法二
index2 = np.where(np.logical_and(a >= 5, a <= 10))
print(index2)
print(a[index2])

# 方法三
d = a[(a <= 10) & (a >= 5)]
print(d)

[6, 9, 10]
<class 'list'>
(array([1, 3, 4], dtype=int64),)
[ 6  9 10]
(array([1, 3, 4], dtype=int64),)
[ 6  9 10]
[ 6  9 10]


#### **15. 如何创建一个python函数来处理scalars并在numpy数组上工作？**

- 难度等级：L2
- 问题：转换适用于两个标量的函数maxx，以处理两个数组
- 给定：
    ```python
    def maxx(x, y):
        """Get the maximum of two items"""
        if x >= y:
            return x
        else:
            return y

    maxx(1, 5)
    ```
- 期望：
    ```python
    a = np.array([5, 7, 9, 8, 6, 4, 5])
    b = np.array([6, 3, 4, 8, 9, 7, 1])
    pair_max(a, b)
    # > array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [78]:
# 其实就是取对应位置的最大值，不过结果好像是小数？
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# 第一种列表的方式
c = []
for i in range(len(a)):
    if a[i] > b[i]:
        c.append(a[i])
    else:
        c.append(b[i])
print(c)
print(type(c))

# 第二种数组的方式
def maxx(x, y):
    '''Get the maximum of two items'''
    if x >= y:
        return x
    else:
        return y

# 猜测这个函数是对两个数组之间的元素进行操作，因为传入的变量是个函数
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

[6, 7, 9, 8, 9, 7, 5]
<class 'list'>


array([6., 7., 9., 8., 9., 7., 5.])

#### **16. 如何交换二维numpy数组中的两列？**

- 难度等级：L2
- 问题：在数组a中交换列1和2

In [79]:
a = np.arange(9).reshape(3, 3)
print(a)

b = a[:, [1, 0, 2]] # 这个操作太秀了
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### **17. 如何交换二维numpy数组中的两行？**

- 难度等级：L2
- 问题：在数组a中交换行1和2

In [80]:
a = np.arange(9).reshape(3, 3)
print(a)

b = a[[1, 0, 2], :]
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### **18. 如何反转二维数组的行？**

- 难度等级：L2
- 问题：反转二维数组a的行

In [85]:
a = np.arange(9).reshape(3, 3)
print(a)

# 其实可以利用索引办到
b = a[:, [2, 1, 0]]
print(b)

# 也可以使用这种方式
c = a[:, ::-1]
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


#### **19. 如何反转二维数组的列？**

- 难度等级：L2
- 问题：反转二维数组a的列

In [86]:
a = np.arange(9).reshape(3, 3)
print(a)

# 其实可以利用索引办到
b = a[[2, 1, 0], :]
print(b)

# 也可以使用这种方式
c = a[::-1]
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

In [91]:
a1 = np.arange(9).reshape(3, 3)
print(a1)

# 这种方式另外叠加了高斯分布
r1 = np.random.randint(low=5, high=10, size=(5, 3)) + np.random.random((5, 3))
print(r1)

# 这种方式应该是均匀分布
r2 = np.random.uniform(5, 10, size=(5, 3))
print(r2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[8.27426319 5.42518513 5.66321944]
 [7.79029098 6.17000599 7.46627917]
 [6.48373141 5.1322764  6.67280872]
 [6.55271869 7.72579994 6.79281088]
 [5.34248555 8.55034851 7.08332065]]
[[6.72647879 7.16454924 6.38363742]
 [6.53839146 9.03222539 8.58890893]
 [8.49328414 7.821488   8.54489683]
 [6.81939388 7.7728169  7.43578192]
 [5.89492953 5.52801393 8.45948305]]


#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **20. 如何创建包含5到10之间随机浮动的二维数组？**

- 难度等级：L2
- 问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数

#### **2. 如何创建一维数组？**

- 难度等级：L1
- 问题：创建从0到9的一维数字数组