# NumPy 100 Exercises

## **说明**

该文档是对[《100 numpy exercises》](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md)的学习笔记。

#### **1. 导入numpy作为np (★☆☆)**

In [1]:
import numpy as np

#### **2. 打印numpy的版本信息和配置 (★☆☆)**

In [2]:
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']


#### **3. 创建一个空矢量，大小为1*10 (★☆☆)**

In [4]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### **4. 寻找数组的内存大小 (★☆☆)**

In [8]:
z = np.zeros((10, 10))
print(z.size)      # 这里的size指的是总共有100个元素
print(z.itemsize)  # 每个元素所占内存（字节）
print('%d bytes' % (z.size * z.itemsize))

100
8
800 bytes


#### **5. 如何从命令行获取numpy add函数的文档？ (★☆☆)**

In [9]:
# 这个有错误
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### **6. 创建一个10维空向量，但是第5个值为1 (★☆☆)**

In [10]:
z = np.zeros(10) # 注意到默认的数据类型为 float
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### **7. 创建一个向量，值为从10到49 (★☆☆)**

In [12]:
z = np.arange(10, 50)
print(z)

# 以下是反向
z_inv = z[::-1]
print(z_inv)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### **8. 反转一个向量 (★☆☆)**

In [17]:
z = np.random.randn(5)
print(z)

z_inv = z[::-1]
print(z_inv)

# 换一种方式
z_inv2 = z[-1:-len(z)-1:-1] # 从倒数第一个到第一个，注意左闭右开
print(z_inv2)

[-0.35875052 -1.45875558 -0.42620173 -2.16807082  0.39448237]
[ 0.39448237 -2.16807082 -0.42620173 -1.45875558 -0.35875052]
[ 0.39448237 -2.16807082 -0.42620173 -1.45875558 -0.35875052]


#### **9. 创建3*3矩阵，值为0到8 (★☆☆)**

In [18]:
z = np.arange(9)
print(z)
z = z.reshape(3, 3)
print(z)
# 其实就是 z = np.arange(9).reshape(3, 3)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### **10. 找出[1,2,0,0,4,0]中的非零值 (★☆☆)**

In [28]:
# 以下是找出索引
z = [1, 2, 0, 0, 4, 0]
print(z != np.zeros(6))

# 以下这种方式更好：
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

# 以下是找出非零值
a = np.array(z)  # 注意这种方式必须用np下的数组才能完成
print(a[a != 0])

[ True  True False False  True False]
(array([0, 1, 4], dtype=int64),)
[1 2 4]


#### **11. 创建3*3单位阵 (★☆☆)**

In [33]:
z = np.eye(3, dtype = 'int') # 其实不用加类型
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### **12. 创建3\*3\*3随机数矩阵 (★☆☆)**

In [34]:
# z = np.random.randn(3, 3, 3)   # 标准正态分布
z = np.random.random((3, 3, 3))  # 连续均匀分布
print(z)

# help(np.random.random)

[[[0.11664449 0.63351755 0.92784217]
  [0.51896247 0.05712764 0.93745489]
  [0.77884356 0.91478212 0.98385281]]

 [[0.70623243 0.44160601 0.57253004]
  [0.25667986 0.34265582 0.61119601]
  [0.20167334 0.70277928 0.58346715]]

 [[0.66233716 0.79452648 0.10580243]
  [0.87992823 0.33173409 0.00696292]
  [0.62366807 0.02809428 0.78805371]]]


#### **13. 创建10*10随机矩阵，寻找最大值和最小值 (★☆☆)**

In [44]:
z = np.random.random((10, 10))
print(z)
print(z.max(), z.min())

# 这种方式是错误的： print(max(z)) # 这种方式只适用于列表
# 思考如果是求每一行或列的最大值呢？
print(z.argmax(axis=0))               # 这里给出的是列最大值索引
print(z[z.argmax(axis=0), range(10)]) # 这里给出的是列最大值

[[0.95088632 0.56600764 0.7294677  0.43752525 0.99693756 0.7422998
  0.52313034 0.91406339 0.30110331 0.1822548 ]
 [0.46253112 0.91834457 0.9076577  0.8824893  0.63205084 0.26880516
  0.50745514 0.59257292 0.94789942 0.79469697]
 [0.3758234  0.69466605 0.85950626 0.43073624 0.51849148 0.71496881
  0.45816944 0.30345832 0.94701962 0.63097613]
 [0.08228683 0.26693147 0.67304554 0.9877871  0.11115968 0.26478558
  0.41468429 0.1767908  0.46844395 0.17431167]
 [0.73117397 0.7361376  0.85553752 0.2602796  0.75676844 0.27091767
  0.68020418 0.26957715 0.00744596 0.88852722]
 [0.61524037 0.74490322 0.16449181 0.09088338 0.51666726 0.40083613
  0.22970519 0.67466263 0.10373652 0.03070908]
 [0.59553654 0.67033925 0.13965304 0.60303764 0.74491118 0.99672614
  0.22179694 0.40945507 0.91188573 0.57003296]
 [0.7717017  0.74663196 0.20016966 0.68119589 0.99591956 0.13058056
  0.09325756 0.42769816 0.86877821 0.20713109]
 [0.55309582 0.21433513 0.52400177 0.80172529 0.64789907 0.96793266
  0.65009285 

#### **14. 创建一个大小为30的随机矩阵，寻找均值 (★☆☆)**

In [45]:
z = np.random.random(30)
# 两种方式
print(np.mean(z))
print(z.mean())

0.49787116690395006
0.49787116690395006


#### **15. 创建一个边界为1，内部为0的二维数组 (★☆☆)**

In [47]:
z = np.zeros((10, 10))
z[0,:]  = 1
z[-1,:] = 1
z[:,0]  = 1
z[:,-1] = 1
print(z)

# 以下这种方式更好
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0 # 注意是左开右闭，-1表示最后一行但不包括，当直接省略-1时候是包括的
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### **16. 如何在现有数组周围添加边框（填充为0） (★☆☆)**

In [48]:
z = np.ones((5, 5))
print(z)

z = np.pad(z, pad_width = 1, mode = 'constant', constant_values = 0)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### **17. 打印输出 (★☆☆)**

In [50]:
# 017. 打印输出
print(0 * np.nan)               # 0乘以nan，结果还是nan
print(np.nan == np.nan)         # nan不等于nan
print(np.inf > np.nan)          # 无穷不大于nan，二者不能比
print(np.nan - np.nan)          # nan减去nan结果还是nan
print(np.nan in set([np.nan]))  # Truw说明 np.nan 确实在 set([np,set])中
print(0.3 == 3 * 0.1)           # 永远不要用==去比较浮点数
print(0.3 == round(3 * 0.1, 2)) # 要这样比较

nan
False
False
nan
True
False
True


#### **18. 生成一个5*5的矩阵，对角线下为1 2 3 4 (★☆☆)**

In [55]:
z  = np.diag(np.arange(1, 5), k = -1) # 这都行？
print(z)

z = np.diag(1 + np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### **19. 生成一个8*8的矩阵，填充为棋盘形式 (★☆☆)**

In [60]:
z = np.zeros((8, 8))
z[1::2, 0::2] = 1 # 对于切片的使用,省略就是最后一行
z[0::2, 1::2] = 1
print(z)

# 换一种填充
z = np.zeros((8, 8))
z[0::2, 0::2] = 1
z[1::2, 1::2] = 1
print(z)

# 注意体会，最终的结果是两次填充的叠加

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### **20. 已知矩阵大小为6\*7\*8，求第100个元素索引处的值 (★☆☆)**

In [62]:
# 这函数用的我没脾气
# 应该是可以将一维索引转换为三维索引
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### **21. 使用tile函数来创建8\*8棋盘矩阵 (★☆☆)**

In [63]:
z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4)) # 将A矩阵按照B重复
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### **22. 将一个5\*5的随机矩阵归一化 (★☆☆)**

In [64]:
# 指的是方差和均值归一化
# 而不是这种大小归一化：z = z/z.max()

z = np.random.random((5, 5))
z = (z - np.mean(z)) / np.std(z) # 这个是标准差
print(z)

[[-0.9663514   0.57393144  1.17132842 -0.40677922 -1.10478623]
 [ 0.65766144  0.14029205 -1.52538247 -0.86474056  0.81095821]
 [-1.54745444  1.1835132   1.13219143  1.41450735 -1.04708107]
 [-0.45555228  0.45561062  1.30500199  0.71345332  1.05951873]
 [ 0.24443944 -1.5254055   0.30060433 -0.18338375 -1.53609508]]


#### **23. 创建一个自定义dtype，将颜色描述为四个无符号字节（RGBA） (★☆☆)**

In [65]:
z = np.dtype([('r', np.ubyte, 1),
              ('g', np.ubyte, 1),
              ('b', np.ubyte, 1),
              ('a', np.ubyte, 1)])
print(z)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### **24. 实现5x3矩阵与3x2矩阵的乘积（实矩阵） (★☆☆)**

In [67]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))

# 两种不同但都可行的方式
z1 = a.dot(b)
z2 = a @ b

print(a)
print(b)
print(z1)
print(z2)

[[0.7412981  0.25855817 0.66367448]
 [0.90427528 0.72289199 0.10048212]
 [0.13808044 0.91866579 0.00561675]
 [0.24813335 0.31106205 0.45185724]
 [0.33364548 0.0376914  0.49396767]]
[[0.85384703 0.60479076]
 [0.73637692 0.18387866]
 [0.94027146 0.71389988]]
[[1.44738563 0.96967071]
 [1.39891422 0.75155592]
 [0.79966514 0.25644261]
 [0.86579531 0.52984726]
 [0.77710098 0.5613598 ]]
[[1.44738563 0.96967071]
 [1.39891422 0.75155592]
 [0.79966514 0.25644261]
 [0.86579531 0.52984726]
 [0.77710098 0.5613598 ]]


#### **25. 给定一维数组，将所有在3到8之间的元素取反 (★☆☆)**

In [5]:
z = np.arange(10)
z[(z > 3) & (z < 8) ] *= -1 # 这个操作太秀了
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### **26. 打印输出 (★☆☆)**

In [1]:
print(sum(range(5), -1)) # 先将 range求和，再跟 -1 求和

from numpy import *
print(sum(range(5), -1)) # sum函数被重置，求和结果不同了 
# print(sum(range(5), axis = -1))

9
10


#### **27. 对整型向量Z，以下哪些表达是合法的？ (★☆☆)**

In [25]:
z = np.array([1, 2, 3, 4, 5, 6, 7])
print(z**z)
print(2 << z >> 2) # 2先左移z位，再右移2位最终结果是，2^z/4 = 2^(z-2)
print(z <- z)
print(1j*z)
print(z/1/1)
print(z<z>z)

[     1      4     27    256   3125  46656 823543]
[ 1  2  4  8 16 32 64]
[False False False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j]
[1. 2. 3. 4. 5. 6. 7.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### **28. 下列表达式的结果 (★☆☆)**

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### **29. 进行远离零的方向取整 (★☆☆)**

In [28]:
# 并不是单一的天花板函数
# 而是先取绝对值，再进行天花板取整，然后再修正符号
# 这个题挺实用的

z = np.random.uniform(-10, +10, 10) # 从 -10 到 +10 有 10 个数
print(z)
print(np.copysign(np.ceil(np.abs(z)), z))

[-5.32897831 -4.42923708  8.99714752 -4.47835173 -6.37852266 -6.01199196
  2.91663463  0.51547406 -6.85171917  3.34697294]
[-6. -5.  9. -5. -7. -7.  3.  1. -7.  4.]


#### **30. 寻找两个数组之间相同的值 (★☆☆)**

In [33]:
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
print(z1)
print(z2)

# 第一种是列表的方法
a = []
for i in z1:
    if i in z2 and i not in a:
        a.append(i)
a = sorted(a) # 进行排序
print(a)
print(type(a))

# 第二种是数组的方式
b = np.intersect1d(z1, z2) # 注意这里是1，而不是l，这函数用的就跟作弊一样
print(b)

[1 3 0 9 1 4 4 3 8 4]
[4 8 6 4 6 7 2 3 8 9]
[3, 4, 8, 9]
<class 'list'>
[3 4 8 9]


#### **31. 如何忽略所有的np的警告？（不推荐） (★☆☆)**

In [36]:
# suicide mode on
defaults = np.seterr(all = "ignore")
z = np.ones(1) / 0

print(z)

#  back to sanity

# 另外一种等价的方式是
with np.errstate(divide = 'ignore'):
    z = np.ones(1) / 0

[inf]


#### **32. 下面的表达式是正确的吗？ (★☆☆)**

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1) # 二者一个返回 nan，另一个返回 1j

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### **33. 如何得到昨天今天和明天的日期？ (★☆☆)**

In [4]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2019-07-28 2019-07-29 2019-07-30


#### **34. 如何得到关于2016年7月的所有日期？ (★★☆)**

In [5]:
# arange 真实一个神奇的函数啊
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### **35. 如何计算(A+B)\*(-A/2)（不用复制） (★★☆)**

In [7]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A, B, out = B)
np.divide(A,2 , out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)

print(A,B)

[-1.5 -1.5 -1.5] [3. 3. 3.]


#### **36. 使用5种不同的方式来计算一个随机矩阵的整数部分 (★★☆)**

In [8]:
z = np.random.uniform(0, 10, 10)
print(z)

print(z - z%1)
print(np.floor(z))
print(np.ceil(z))
print(z.astype(int))
print(np.trunc(z)) # 这个暂时不知道是什么意思，存疑吧

[3.89646867 8.36027004 9.76215534 6.5533294  8.11035813 5.16963373
 1.19214778 8.12431399 0.29626936 8.19330068]
[3. 8. 9. 6. 8. 5. 1. 8. 0. 8.]
[3. 8. 9. 6. 8. 5. 1. 8. 0. 8.]
[ 4.  9. 10.  7.  9.  6.  2.  9.  1.  9.]
[3 8 9 6 8 5 1 8 0 8]
[3. 8. 9. 6. 8. 5. 1. 8. 0. 8.]


#### **37. 创建一个5*5的矩阵，其中行数值从0至4 (★★☆)**

In [22]:
# 指每一行都是从0到4

z = np.ones((5,1))*np.arange(0,5) # 这种方式也是广播了，*是元素乘
print(z)

# 这种方式才是矩阵乘法
# 特别主要要在 np.arange(5) 外边加上 []
# 这样保证其形状是 (1, 5) 而不是 (5,)
z1 = np.ones((5,1)).dot([np.arange(5)])
print(z1)

# 这是使用广播的方式
z2 = np.zeros((5, 5))
z2 += np.arange(5)
print(z2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### **38. 创建一个函数来生成10个整数，并用其来创建矩阵 (★☆☆)**

In [23]:
# 这其实就是一个生成器
def generator():
    for x in range(10):
        yield x
z = np.fromiter(generator(), dtype = float, count = -1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### **39. 创建一个10维的向量，它的值从0到1（不包括0和1） (★★☆)**

In [24]:
z = np.linspace(0, 1, 11, endpoint = False)[1:]
print(z)

# 这个有点秀啊
# endpoint 控制不会取到1，后边的[1:] 将首位0给排除除去

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### **40. 创建一个10维的随机数组并且排序 (★★☆)**

In [25]:
z = np.random.random(10)
z.sort()
print(z)

[0.03535688 0.0499947  0.18598057 0.19512892 0.20947808 0.28189129
 0.33780924 0.83946653 0.84452827 0.88433212]


#### **41. 如何对一个小数组快速求和？（比np.sum更快） (★★☆)**

In [26]:
z = np.arange(10)

# 这个没看懂
print(np.add.reduce(z))

# 这个是矩阵相乘
print(z.dot(np.ones((10, 1), dtype = int)))

45
[45]


#### **42. 检查两个随机矩阵是否相等 (★★☆)**

In [27]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A, B)
print(equal)

equal = np.array_equal(A, B)
print(equal)

False
False


#### **43. 使数组不可变（只读） (★★☆)**

In [28]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### **44. 若10\*2的数组存储着笛卡尔坐标，转换为极坐标 (★★☆)**

In [30]:
z = np.random.random((10,2))
x,y = z[:,0],z[:,1] # 这种赋值方式需要学习

# 直接利用公式
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)

print(r)
print(t)

[0.96606095 0.41956829 1.02604044 0.85435302 0.06899294 0.49997685
 0.55082926 0.14326906 0.66889473 0.87355624]
[0.74050416 0.5561809  1.25458524 0.14125606 0.05970711 0.14611368
 0.45944812 0.05816625 0.25486273 0.85710539]


#### **创建一个10维的向量，将最大值替换为0 (★★☆)**

In [32]:
a = np.random.random(10)
print(a)

z = a
z[z.argmax()] = 0
print(z)

# 使用更加底层的方法实现一遍
# 首先找到最大值和索引
max_value = 0
max_index = 0
for i in range(len(a)):
    if a[i] >= max_value:
        max_value = a[i]
        max_index = i
a[max_index] = 0
print(a)

[0.01428117 0.81731075 0.91236795 0.6647293  0.9186818  0.90971014
 0.78407816 0.83306642 0.74459638 0.41232486]
[0.01428117 0.81731075 0.91236795 0.6647293  0.         0.90971014
 0.78407816 0.83306642 0.74459638 0.41232486]
[0.01428117 0.81731075 0.         0.6647293  0.         0.90971014
 0.78407816 0.83306642 0.74459638 0.41232486]


#### **46. 创建一个结构数组，具有x和y坐标，覆盖 [0,1]x[0,1]的区域 (★★☆)**

In [33]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

In [34]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666


#### **48. 打印每个numpy标量的最小和最大可表示值类型 (★★☆)**

In [37]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### **49. 如何打印数组中的所有值 (★★☆)**

In [38]:
np.set_printoptions(threshold=np.nan)
z = np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### **50. 如何在向量中找到最接近的值（给定标量）？ (★★☆)**

In [41]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

71


#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**

#### **47. 给定两个数组 X 和 Y ，组合为柯西矩阵 C (Cij =1/(xi - yj)) (★★☆)**