# NumPy 100 Exercises

## 说明

该文档是对[《100 numpy exercises》](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md)的学习笔记。

#### **1. 导入numpy作为np (★☆☆)**

In [1]:
import numpy as np

#### **2. 打印numpy的版本信息和配置 (★☆☆)**

In [2]:
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']


In [7]:
# 003. 创建一个空矢量，大小为1*10
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# 004. 寻找数组的内存大小
z = np.zeros((10, 10))
print('%d bytes' % (z.size * z.itemsize))

800 bytes


In [10]:
# 005. 如何从命令行获取numpy add函数的文档?(这个有错误)
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [11]:
# 006. 创建一个10维空向量，但是第五个值为1
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
# 007. 创建一个向量，值为从10到49
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
# 008. 反转一个向量
z = np.random.randn(5)
print(z)
z = z[::-1]
# 其实就是这样 z = z[-1:-len(z)-1:-1] # 注意切片是左闭右开，即-6取不到
print(z)

[-0.27373847 -1.41541707  0.87601102  0.24268626  0.35244086]
[ 0.35244086  0.24268626  0.87601102 -1.41541707 -0.27373847]


In [28]:
# 009. 创建3*3矩阵，值为0-8
z = np.arange(9)
print(z)
z = z.reshape(3, 3)
print(z)
# 其实就是 z = np.arange(9).reshape(3, 3)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
# 010. 找打[1,2,0,0,4,0]中的非零值
z = [1, 2, 0, 0, 4, 0]
print(z != np.zeros(6))

# 以下这种方式更好：
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

[ True  True False False  True False]
(array([0, 1, 4], dtype=int64),)


In [36]:
# 011. 创建3*3单位阵
z = np.eye(3, dtype = 'int') # 其实不用加类型
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [48]:
# 012. 创建3*3*3随机数矩阵
# z = np.random.randn(3, 3, 3)
z = np.random.random((3, 3, 3))
print(z)

[[[0.88557545 0.68649777 0.95765894]
  [0.75802464 0.67394256 0.3529453 ]
  [0.28021301 0.10750878 0.84291621]]

 [[0.67015972 0.19780504 0.21674252]
  [0.87086932 0.63519985 0.93498093]
  [0.08281387 0.40821043 0.20731718]]

 [[0.77671393 0.59237365 0.29792127]
  [0.67063528 0.94833585 0.59026789]
  [0.09171436 0.53757756 0.6546771 ]]]


In [64]:
# 013. 创建10*10随机矩阵，寻找最大值和最小值
z = np.random.random((10, 10))
# 这种方式是错误的： print(max(z))
print(z)
print(z.max(), z.min())

[[0.20612378 0.52306298 0.10344354 0.62994616 0.74532132 0.01653298
  0.18394747 0.86161593 0.85913831 0.84597241]
 [0.49421315 0.44613164 0.92952183 0.45677561 0.77175131 0.41292667
  0.11259697 0.38940996 0.39433471 0.42242741]
 [0.93808614 0.26352511 0.29417552 0.63091136 0.68307549 0.32600848
  0.94765378 0.36893728 0.22772135 0.64627616]
 [0.94187348 0.75391564 0.6097022  0.8830448  0.55201463 0.65647114
  0.67330132 0.48021927 0.20607205 0.99672788]
 [0.86132194 0.72217411 0.33683539 0.29688662 0.89475179 0.01936498
  0.83943828 0.73970752 0.63267559 0.59709991]
 [0.16703719 0.48725798 0.83957448 0.37786021 0.23657772 0.36020693
  0.56948241 0.19124082 0.95077664 0.15938667]
 [0.34833565 0.85326927 0.99694999 0.38174529 0.15568101 0.20155604
  0.52047592 0.33959764 0.28730945 0.85115919]
 [0.79665095 0.2246879  0.1385434  0.81080899 0.18205349 0.98830637
  0.75072248 0.53141695 0.48602058 0.20396668]
 [0.13022255 0.70301854 0.2345329  0.30113778 0.26952324 0.21594963
  0.23494822

In [65]:
# 014. 创建随机矩阵30，寻找均值
z = np.random.random(30)
# 两种方式
print(np.mean(z))
print(z.mean())

0.5895578309618094
0.5895578309618094


In [81]:
# 015. 创建一个边界为1，内部为0的二维数组
z = np.zeros((10, 10))
z[0,:] = 1
z[-1,:] = 1
z[:,0] = 1
z[:,-1] = 1
print(z)

# 以下这种方式更好
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0 # 注意是左开右闭，-1表示最后一行但不包括，当直接省略-1时候是包括的
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
# 016. 如何在现有数组周围添加边框(填充为0)
z = np.ones((5, 5))
print(z)
z = np.pad(z, pad_width = 1, mode = 'constant', constant_values = 0)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [27]:
# 017. 打印输出
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan])) # Truw说明 np.nan 确实在 set([np,set])中
print(0.3 == 3 * 0.1) # 永远不要用==去比较浮点数
print(0.3 == round(3 * 0.1, 2)) # 要这样比较

nan
False
False
nan
True
False
True


In [30]:
# 018. 矩阵5*5，对角线下为1 2 3 4
z  = np.diag(np.arange(1, 5), k = -1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [35]:
# 019. 矩阵8*8，填充矩阵形式时
z = np.zeros((8, 8))
z[1::2, 0::2] = 1 # 对于切片的使用,省略就是最后一行
z[0::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [36]:
# 020. 矩阵6*7*8，第100个元素索引处的值
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


In [38]:
# 021. 使用tile函数来创建8*8期盼
z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4)) # 将A矩阵按照B重复
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
# 022. 将一个5*5随机矩阵归一化
z = np.random.random((5, 5))
# z = z/z.max()
# 指的是方差和均值归一化
z = (z - np.mean(z)) / np.std(z) # 这个是标准差
print(z)

[[-0.73293802 -1.16350111 -0.68292942 -0.66567597 -0.52388416]
 [-0.84902169 -0.4325723   0.64031504  1.63239613  1.88430633]
 [-1.27428885 -1.18892807  1.08161916  0.49520682 -1.43350259]
 [ 1.28936855  1.00160265 -1.26448205  0.83622275 -0.95080991]
 [ 0.40432314  0.88851626  0.42799415  0.88689767 -0.30623451]]


In [43]:
# 023. 创建一个自定义dtype，将颜色描述为四个无符号字节（RGBA）
z = np.dtype([('r', np.ubyte, 1),
              ('g', np.ubyte, 1),
              ('b', np.ubyte, 1),
              ('a', np.ubyte, 1)])
print(z)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [46]:
# 024. 将5x3矩阵乘以3x2矩阵（实矩阵乘积
z = np.random.random((5, 3)).dot(np.random.random((3, 2)))
print(z)

[[0.43354405 0.19834419]
 [0.19919898 0.10419883]
 [0.69993707 0.26274176]
 [0.4218447  0.1494242 ]
 [0.3610132  0.1305477 ]]


In [53]:
# 025. 给定一维数组，否定所有在3到8之间的元素
z = np.arange(10)
z[(z > 3) & (z < 8) ] *= -1 # 这个操作太秀了
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [60]:
# 026. 打印输出
print(sum(range(5), -1)) # 先将 range求和，再跟 -1 求和
#from numpy import *
print(sum(range(5), -1)) # 加上中间那一句后，求和结果不同了 
# print(sum(range(5), axis = -1))

10
10


In [15]:
# 027. 以下哪些表达是合法的
z = 1
print(z**z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
print(z<z>z)

1
1
False
1j
1.0
False


In [19]:
# 028. 接下来表达什么
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


d:\program_new\python\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
d:\program_new\python\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [21]:
# 029. 进行远离零的取整
z = np.random.uniform(-10, +10, 10) # 从 -10 到 +10 有 10 个数
print(z)
print(np.copysign(np.ceil(np.abs(z)), z)) # 先取绝对值，再进行天花板取整，然后再赋号

[-9.95892804  2.46395059  5.34296987 -8.56674996  3.17466068  4.50696948
 -6.03541872 -9.54095109 -2.26408482  7.25400464]
[-10.   3.   6.  -9.   4.   5.  -7. -10.  -3.   8.]


In [16]:
# 030. 寻找两个数组之间相同的值
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
print(z1)
print(z2)
print(np.intersect1d(z1, z2)) # 这里是1，而不是l

[6 0 0 2 9 9 4 4 5 9]
[5 2 3 7 4 9 0 4 7 3]
[0 2 4 5 9]


In [28]:
# 031. 忽略所有的np的警告

# suicide mode on
defaults = np.seterr(all = "ignore")
z = np.ones(1) / 0

print(z)

#  back to sanity

# 另外一种等价的方式是
with np.errstate(divide = 'ignore'):
    z = np.ones(1) / 0

[inf]


In [29]:
# 032. 下面的表达式正确吗
np.sqrt(-1) == np.emath.sqrt(-1) # 二者一个返回 nan，另一个返回 1j

False

In [33]:
# 033. 得到昨天今天和明天的日期
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2019-06-04 2019-06-05 2019-06-06


In [35]:
# 34. 得到两个时间点之间所有的日期
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [13]:
# 35. 如何计算（A+B）*(-A/2)不用复制
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A, B, out = B)
np.divide(A,2 , out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)
print(A,B)

[-1.5 -1.5 -1.5] [3. 3. 3.]


In [17]:
# 36. 使用5种不同的方式来计算一个随机矩阵的整数部分
z = np.random.uniform(0, 10, 10)
print(z)

print(z - z%1)
print(np.floor(z))
print(np.ceil(z))
print(z.astype(int))
print(np.trunc(z)) # 这个暂时不知道是什么意思，存疑吧

[2.80915162 8.23123092 6.84228932 0.3119505  8.35223812 1.75983088
 0.32371248 6.44481786 9.89338693 0.46682242]
[2. 8. 6. 0. 8. 1. 0. 6. 9. 0.]
[2. 8. 6. 0. 8. 1. 0. 6. 9. 0.]
[ 3.  9.  7.  1.  9.  2.  1.  7. 10.  1.]
[2 8 6 0 8 1 0 6 9 0]
[2. 8. 6. 0. 8. 1. 0. 6. 9. 0.]


In [23]:
# 37. 创建一个5*5的矩阵，其中行数值从0至4(指每一行都是从0到4)
z = np.ones((5,1))*np.arange(0,5)
print(z)

z2 = np.zeros((5, 5))
z2 += np.arange(5)
print(z2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [24]:
# 38. 创建一个函数来生成10个整数，并用其来创建矩阵
def generator():
    for x in range(10):
        yield x                          # 好吧这个有点麻烦，暂时就不管了
z = np.fromiter(generator(), dtype = float, count = -1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [25]:
# 39. 创建一个10维的向量，它的值从0到1，（不包括0和1）
z = np.linspace(0, 1, 11, endpoint = False)[1:]
print(z)
# endpoint 控制不会取到1，后边的[1:] 将首位0给排除除去

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [27]:
# 40. 创建一个10维的随机数组并且排序
z = np.random.random(10)
z.sort()
print(z)

[0.1429935  0.19956969 0.49310394 0.56329461 0.67487842 0.89699164
 0.91679018 0.95765188 0.97364357 0.99311313]


In [55]:
# 41. 对一个小数组快速求和
z = np.arange(10)
print(np.add.reduce(z))
print(z.dot(np.ones((10, 1), dtype = int)))

45
[45]


In [56]:
# 42. 检查两个随机矩阵是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A, B)
print(equal)

equal = np.array_equal(A, B)
print(equal)

False
False


In [59]:
# 43. 使数组不可变，只读
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [62]:
# 44. 10*2的数组存储着笛卡尔坐标，转换为极坐标
z = np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.39613239 0.66468174 1.00392026 1.0126403  0.81942167 0.69493968
 0.95995072 0.94743883 1.1102572  1.0456906 ]
[1.29875655 0.48069554 0.20000819 1.19702683 1.52451954 1.18159735
 1.31659614 1.53063452 0.66629809 1.20579518]


In [63]:
# 45. 创建一个10维的向量，将最大值替换为0
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.59458973 0.17666947 0.         0.00624669 0.37093399 0.11587892
 0.49772159 0.42408864 0.75416001 0.66503468]


In [64]:
# 46. 创建一个结构数组，具有x和y坐标，覆盖0101区域
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [65]:
# 47. 给定两个数组，组合为柯西矩阵
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666
